refresh_rate_ms: 1000
debug_mode: true

states:
  game:
    keybinds:
      "F8":
        action: "test_click"
        description: "Test Klick Phase 6"
      "1":
        action: "skill_1"
        description: "Primärer Skill"
      "2":
        action: "skill_2"
      "3":
        action: "skill_3"
      "4":
        action: "skill_4"
      "5":
        action: "skill_5"
      "6":
        action: "skill_6"
      "7":
        action: "skill_7"
      "8":
        action: "skill_8"
      "9":
        action: "skill_9"
      "W":
        action: "move_forward"
  inventory:
    keybinds:
      "ESC":
        action: "back_button_click"
        description: "Zurück-Button oben links"
